### ISSUE TITLE
Does the raspberry pi zero 2 fit/work?

### ISSUE THREAD

**Issue by spitfire** [Chrismettal/flipper-zero-backpacks#2]
Does the raspberry pi zero 2 fit the backpack/work with pwnagotchi?

**Comment by Chrismettal** [comment]
Mechanically the 2 should fit just fine, and since the UART is still in the same place, communication with the Flipper through this backpack will also work, so the backpacks itself have no reason not to work with Zero 2's.

However, I remember some talk within the Pwnagotchi project itself about the Zero 2 not being easily compatible, though some people seem to have managed it. Pwnagotchi is a different project entirely though so Pi compatibility would best be discussed over there.


I personally don't have access to a Zero 2 so I am unable to test on my side for now. If someone sent me a Zero 2 i'd love to confirm. Obiously if someone else tests this I'll update the description as well.

**Comment by spitfire** [comment]
Thanks for the information, I was asking about the physical side, and I know I have to do my research on the Pwnagotchi side. I'll let you know if I learn anything
